### ISSUE TITLE
Add support for natively importing  XRD data formats

### ISSUE THREAD

**Issue by lktsui** [lktsui/carbon_xs_gui#11]
It would be nice to support natively importing data formats from the XRD systems that are commonly used.

**Comment by lktsui** [comment]
Supported formats:

- [x]  Jade *.mdi
- [x] Rigaku *.ras
- [x] PanAnalytical *.xy

**Comment by edward651** [comment]
Yes - could you include support for Rigaku MiniFlex systems?  File is very simple.
First line is sample title.
Data is in angle / intensity format separated by a space.

Thanks,
Ed.

**Comment by lktsui** [comment]
Hi @edward651,

Could you please attach an example data file (or email one me?) so I can verify that it loads properly?

Thanks!
-Lok-kun

**Comment by edward651** [comment]
Here it is.  It is from a Rigaku miniflex.


Ed.


________________________________

**Comment by lktsui** [comment]
@edward651 

Hi Ed,

Thanks for the example. This'll make integrating the import a lot easier. What's the filename extension used by the miniflex in their data files? For instance .txt / .mdi / .dat ?

-Lok-kun Tsui

**Comment by edward651** [comment]
.txt is what comes out of Jade 5.0 that we are using.


________________________________

**Comment by lktsui** [comment]
I have added support for loading the Miniflex data format and also any text files with arbitrary numbers of headers in commit 09f3b9c2cde12dfe771a16e454680d1d4ef3bda0.

It will be available in the next release version

**Comment by darkwraith** [comment]
Panalytical XRD instruments output files in *.xrdml file type. An example is attached. Currently I use highscore to convert this file into a general ascii file with 2 or 3 columns which work in carbonxs gui but a one step solution would be very helpful. 

Github didn't like the file types so I renamed them both to have the .txt extension. 
[Panalytical File type Example.xrdml.txt](https://github.com/lktsui/carbon_xs_gui/files/3315511/Panalytical.File.type.Example.xrdml.txt)

[Panalytical File type Example.ASC.txt](https://github.com/lktsui/carbon_xs_gui/files/3315515/Panalytical.File.type.Example.ASC.txt)

**Comment by lktsui** [comment]
Hello,

Can you use the export from Pananalytical's software to .xy? We should be able to read it in that format which is what we do on our Pananalytical XRD. XRDML is a very complicated format that I am not sure I would have time to write a parser for in the near future.

Best regards,

Lok-kun Tsui
Research Assistant Professor
University of New Mexico - Center for Micro-Engineered Materials

________________________________________

**Comment by darkwraith** [comment]
I didn't know Panalytical's data viewer exported to that format. I confirmed this works so feel free to ignore my request as I understand how complicated the xrdml format is. I'm surprised the old version of highscore I use doesn't have this *.xy export capability but I guess there are reasons to update software. Thanks for the quick response!

**Comment by kakou-i** [comment]
Hello

I want to use CarbonXS GUI to perform XRD analysis on graphite, but I always get an error when importing .xy data. The error message is
 "Traceback (most recent call last):
  File "CarbonXS_GUI.py", line 980, in open_pattern
  File "CarbonXS_GUI.py", line 88, in write
UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-47: ordinal not in range(128)". Even when importing ASCII files converted by Highscore, the same error message is displayed. How can I solve this problem?

Thanks
Hua

**Comment by kakou-i** [comment]
> Hello 你好
> 
> I want to use CarbonXS GUI to perform XRD analysis on graphite, but I always get an error when importing .xy data. The error message is我想用 CarbonXS 图形用户界面（GUI）对石墨进行 XRD 分析，但每次导入 .xy 数据时都会出错。错误提示是 "Traceback (most recent call last):“回溯（最近一次调用最后）： File "CarbonXS_GUI.py", line 980, in open_pattern文件 "CarbonXS_GUI.py"，第 980 行，在 open_pattern 中 File "CarbonXS_GUI.py", line 88, in write文件 "CarbonXS_GUI.py"，第 88 行，在 write 中 UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-47: ordinal not in range(128)". Even when importing ASCII files converted by Highscore, the same error message is displayed. How can I solve this problem?UnicodeEncodeError：'ascii' 编码器无法在位置 43 - 47 处编码字符：序号不在范围（128）内。即使导入由 Highscore 转换的 ASCII 文件，也会显示相同的错误消息。我该如何解决这个问题？
> 
> Thanks 谢谢 Hua 圆圆

Solved! It turns out the path couldn't contain Chinese characters. This is fantastic software, thanks for sharing!

**Comment by lokkuntsui** [comment]
Hi @kakou-i ,

Embarrassingly, I have lost my old Github login so this is a new account. Thanks for your interest in the software and I am happy it is working out for you. If you can send me copy of the file that didn't work with Chinese characters, I can work on integrating the loading of non-ASCII data files into the program. 

I am working on a new version over here, but it is not quite ready yet: https://gitlab.com/lktsui1/carbon_xs_gui_2 (It is a pure python implementation so no more Fortran dependency)

**Comment by kakou-i** [comment]
> Hi [@kakou-i](https://github.com/kakou-i) ,
> 
> Embarrassingly, I have lost my old Github login so this is a new account. Thanks for your interest in the software and I am happy it is working out for you. If you can send me copy of the file that didn't work with Chinese characters, I can work on integrating the loading of non-ASCII data files into the program.
> 
> I am working on a new version over here, but it is not quite ready yet: https://gitlab.com/lktsui1/carbon_xs_gui_2 (It is a pure python implementation so no more Fortran dependency)

I apologize for not describing it clearly. The problem I'm encountering seems to be that the file storage path cannot contain Chinese characters. The software seems to search for the file path when it calls it, but it cannot recognize Chinese characters. My XRD data file does not contain any Chinese characters; it's simply two columns of x and y data.

**Comment by lokkuntsui** [comment]
I'll add it to the list of things to fix in the new version. Thanks for the clarification.

https://gitlab.com/lktsui1/carbon_xs_gui_2/-/work_items/1
